name: Run Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: [8.1, 8.2, 8.3]

        name: PHP ${{ matrix.php-version }} test

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, json
                  coverage: none

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run PHPUnit
              run: ./vendor/bin/phpunit --testdox tests
